### ISSUE TITLE
Return anonymous user

### ISSUE THREAD

**Issue by leebrooks0** [dcramer/mock-django#31]
Is this line correct:

https://github.com/dcramer/mock-django/blob/master/mock_django/http.py#L62

Should it not be ```if user is None```?

If I don't pass in a user I get ```None``` for ```request.user```

**Comment by frewsxcv** [comment]
9ba5c8584fe01d054e2178a10692e6d063c06c62

**Comment by leebrooks0** [comment]
Another thing, should this line

https://github.com/dcramer/mock-django/blob/master/mock_django/http.py#L63

not read ```user = self.user```?

**Comment by leebrooks0** [comment]
Sorry I see it is not a class, what i meant was that

```user = AnonymousUser()```?

**Comment by frewsxcv** [comment]
6d39d1f3816da61ea613f9717390e65ee6f3958e

**Comment by frewsxcv** [comment]
Thanks @leebrooks0

**Comment by leebrooks0** [comment]
Thanks for the fix, any chance you could push a new version to pypi?

**Comment by frewsxcv** [comment]
Done https://pypi.python.org/pypi/mock-django/0.6.7

**Comment by leebrooks0** [comment]
Thanks
